const routes = {
  HOME: "/",
  ABOUT: "/about",
  ACCOUNT: "/account",
  ADDRESSES: "/account/addresses",
  ORDERS: "/account/orders",
  SETTINGS: "/account/settings",
  WISHLIST: "/account/wishlist",
  CAREERS: "/careers",
  CART: "/cart",
  CONTACT: "/contact",
  FAQS: "/faqs",
  LOGOUT: "/logout",
  RETURNS: "/returns",
  SHIPPING: "/shipping",
  SHOP: "/shop",
  ACCESSORIES: "/shop/accessories",
  MEN: "/shop/men",
  NEW_ARRIVALS: "/shop/new",
  SALE: "/shop/sale",
  WOMEN: "/shop/women",
  SIZE_GUIDE: "/size-guide",
  STORES: "/stores",
  SUSTAINABILITY: "/sustainability",
};

export default routes;
