#!/bin/bash
# Auto-generated migration script

gh issue edit 116 --remove-label "documentation" --add-label "type: documentation"
gh issue edit 113 --remove-label "frontend" --add-label "area: frontend"
gh issue edit 112 --remove-label "frontend" --add-label "area: frontend"
gh issue edit 111 --remove-label "frontend" --add-label "area: frontend"
gh issue edit 110 --remove-label "frontend" --add-label "area: frontend"
gh issue edit 109 --remove-label "frontend" --add-label "area: frontend"
gh issue edit 107 --remove-label "frontend" --add-label "area: frontend"
gh issue edit 106 --remove-label "frontend" --add-label "area: frontend"
gh issue edit 105 --remove-label "frontend" --add-label "area: frontend"
gh issue edit 104 --remove-label "frontend" --add-label "area: frontend"
gh issue edit 103 --remove-label "enhancement" --add-label "type: enhancement"
gh issue edit 98 --remove-label "enhancement" --add-label "type: enhancement"
gh issue edit 98 --remove-label "frontend" --add-label "area: frontend"
gh issue edit 95 --remove-label "enhancement" --add-label "type: enhancement"
gh issue edit 95 --remove-label "frontend" --add-label "area: frontend"
gh issue edit 94 --remove-label "documentation" --add-label "type: documentation"
gh issue edit 86 --remove-label "documentation" --add-label "type: documentation"
gh issue edit 80 --remove-label "documentation" --add-label "type: documentation"
gh issue edit 80 --remove-label "high priority" --add-label "priority: high"
gh issue edit 77 --remove-label "enhancement" --add-label "type: enhancement"
gh issue edit 77 --remove-label "frontend" --add-label "area: frontend"
gh issue edit 77 --remove-label "medium priority" --add-label "priority: medium"
gh issue edit 76 --remove-label "enhancement" --add-label "type: enhancement"
gh issue edit 76 --remove-label "frontend" --add-label "area: frontend"
gh issue edit 76 --remove-label "medium priority" --add-label "priority: medium"
gh issue edit 75 --remove-label "enhancement" --add-label "type: enhancement"
gh issue edit 75 --remove-label "frontend" --add-label "area: frontend"
gh issue edit 75 --remove-label "medium priority" --add-label "priority: medium"
gh issue edit 74 --remove-label "enhancement" --add-label "type: enhancement"
gh issue edit 74 --remove-label "frontend" --add-label "area: frontend"
gh issue edit 74 --remove-label "medium priority" --add-label "priority: medium"
gh issue edit 73 --remove-label "enhancement" --add-label "type: enhancement"
gh issue edit 73 --remove-label "frontend" --add-label "area: frontend"
gh issue edit 73 --remove-label "medium priority" --add-label "priority: medium"
gh issue edit 72 --remove-label "enhancement" --add-label "type: enhancement"
gh issue edit 72 --remove-label "frontend" --add-label "area: frontend"
gh issue edit 72 --remove-label "medium priority" --add-label "priority: medium"
gh issue edit 71 --remove-label "enhancement" --add-label "type: enhancement"
gh issue edit 71 --remove-label "frontend" --add-label "area: frontend"
gh issue edit 71 --remove-label "medium priority" --add-label "priority: medium"
gh issue edit 70 --remove-label "enhancement" --add-label "type: enhancement"
gh issue edit 70 --remove-label "frontend" --add-label "area: frontend"
gh issue edit 70 --remove-label "medium priority" --add-label "priority: medium"
gh issue edit 69 --remove-label "frontend" --add-label "area: frontend"
gh issue edit 69 --remove-label "high priority" --add-label "priority: high"
gh issue edit 54 --remove-label "enhancement" --add-label "type: enhancement"
gh issue edit 54 --remove-label "frontend" --add-label "area: frontend"
gh issue edit 54 --remove-label "medium priority" --add-label "priority: medium"
gh issue edit 52 --remove-label "frontend" --add-label "area: frontend"
gh issue edit 52 --remove-label "low priority" --add-label "priority: low"
gh label create "cleanup" --description "Code cleanup (debug statements, etc.)" --color "ffc107" --force
gh label create "performance" --description "Performance optimization needed" --color "28a745" --force
gh label create "refactoring" --description "Code restructuring and cleanup" --color "6f42c1" --force
gh label create "good first issue" --description "Good for newcomers to the project" --color "7057ff" --force
gh label create "help wanted" --description "Extra attention is needed from community" --color "008672" --force